extends Node

enum AreaType {GRAV, OBJECT}
enum SpawnerShape {Circle, Rect}
enum obj_type {PLANET, UNIT}

var planet_parts = {
	spheres = ["res://Project/Images/planets/Parts/sphere0.png", "res://Project/Images/planets/Parts/sphere1.png", "res://Project/Images/planets/Parts/sphere2.png"],
	noises = ["res://Project/Images/planets/Parts/noise00.png", "res://Project/Images/planets/Parts/noise01.png", "res://Project/Images/planets/Parts/noise02.png", "res://Project/Images/planets/Parts/noise03.png", "res://Project/Images/planets/Parts/noise04.png", "res://Project/Images/planets/Parts/noise05.png", "res://Project/Images/planets/Parts/noise06.png", "res://Project/Images/planets/Parts/noise07.png", "res://Project/Images/planets/Parts/noise08.png", "res://Project/Images/planets/Parts/noise09.png", "res://Project/Images/planets/Parts/noise10.png", "res://Project/Images/planets/Parts/noise11.png", "res://Project/Images/planets/Parts/noise12.png", "res://Project/Images/planets/Parts/noise13.png", "res://Project/Images/planets/Parts/noise14.png", "res://Project/Images/planets/Parts/noise15.png", "res://Project/Images/planets/Parts/noise16.png", "res://Project/Images/planets/Parts/noise17.png", "res://Project/Images/planets/Parts/noise18.png", "res://Project/Images/planets/Parts/noise19.png", "res://Project/Images/planets/Parts/noise20.png", "res://Project/Images/planets/Parts/noise21.png", "res://Project/Images/planets/Parts/noise22.png", "res://Project/Images/planets/Parts/noise23.png", "res://Project/Images/planets/Parts/noise24.png", "res://Project/Images/planets/Parts/noise25.png", "res://Project/Images/planets/Parts/noise26.png", "res://Project/Images/planets/Parts/noise27.png"],
	lights = ["res://Project/Images/planets/Parts/light0.png", "res://Project/Images/planets/Parts/light1.png", "res://Project/Images/planets/Parts/light2.png", "res://Project/Images/planets/Parts/light3.png", "res://Project/Images/planets/Parts/light4.png", "res://Project/Images/planets/Parts/light5.png", "res://Project/Images/planets/Parts/light6.png", "res://Project/Images/planets/Parts/light7.png", "res://Project/Images/planets/Parts/light8.png", "res://Project/Images/planets/Parts/light9.png", "res://Project/Images/planets/Parts/light10.png"]
}

var random_colors = [
	Color.aqua,
	Color.aquamarine,
	Color.bisque,
	Color.blueviolet,
	Color.blue,
	Color.burlywood,
	Color.brown,
	Color.cadetblue,
	Color.chartreuse,
	Color.chocolate,
	Color.coral,
	Color.cornflower,
	Color.cornsilk,
	Color.crimson,
	Color.cyan,
	Color.darkblue,
	Color.darkcyan,
	Color.darkgoldenrod,
	Color.darkgray,
	Color.darkgreen,
	Color.darkkhaki,
	Color.darkmagenta,
	Color.darkolivegreen,
	Color.darkorange,
	Color.darkorchid,
	Color.darkred,
	Color.darksalmon,
	Color.darkseagreen,
	Color.darkslateblue,
	Color.darkslategray,
	Color.darkturquoise,
	Color.darkviolet,
	Color.deeppink,
	Color.deepskyblue,
	Color.dimgray,
	Color.dodgerblue,
	Color.firebrick,
	Color.floralwhite,
	Color.forestgreen,
	Color.fuchsia,
	Color.gainsboro,
	Color.gold,
	Color.ghostwhite,
	Color.goldenrod,
	Color.gray,
	Color.green,
	Color.greenyellow,
	Color.honeydew,
	Color.hotpink,
	Color.indianred,
	Color.indigo,
	Color.ivory,
	Color.khaki,
	Color.lavender,
	Color.lavenderblush,
	Color.lawngreen,
	Color.lemonchiffon,
	Color.lightblue,
	Color.lightcoral,
	Color.lightcyan,
	Color.lightgoldenrod,
	Color.lightgray,
	Color.lightgreen,
	Color.lightpink,
	Color.lightsalmon,
	Color.lightseagreen,
	Color.lightskyblue,
	Color.lightslategray,
	Color.lightsteelblue,
	Color.lightyellow,
	Color.lime,
	Color.limegreen,
	Color.magenta,
	Color.maroon
]

var player = null
